name: 'Update walkable zones'

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *' # every day

jobs:
  update_walkable_zones:
    if: "!contains(github.event.head_commit.message, 'Update walkable zones') && !contains(github.event.head_commit.message, 'zone walk') && !contains(github.event.head_commit.message, 'Stats update')"
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
      with:
        ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}
        persist-credentials: true
    - uses: actions/setup-python@v4
      with:
        python-version: '2.7.18'
        cache: 'pip'
    - run: pip install -r requirements.txt
    - run: ./build-walkable-zones.sh
    - name: Commit files
      run: |
        git config --local user.email "zone-walks@chary.us"
        git config --local user.name "Zone Walks GitHub Action"
        git add ./walkable-zones.json ./.github/workflows/walk.yaml
        git commit -m "Update walkable zones ($(date -u +"%x %H:%M"))" --allow-empty
        git push
